version: '3.5'
services:

  api_app:
    image: easycam_api_app
    container_name: easycam_api_app
    env_file:
      - api/.env
    build:
      context: api
      dockerfile: Dockerfile
    networks:
      - easycam
    ports:
      - 9086:9086
      - 3086:3086
    restart: always
    depends_on:
      - api_nginx
  api_nginx:
    image: easycam_api_nginx
    container_name: easycam_api_nginx
    build:
      context: api
      dockerfile: Dockerfile.nginx
    networks:
      - easycam
    ports:
      - 8086:8086
    restart: always

  client:
    image: easycam_client
    container_name: easycam_client
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - easycam
    ports:
      - 8087:8087
    restart: always

networks:
  easycam:
    name: easycam
    driver: bridge
